<?xml version="1.0" encoding="utf-8"?><Database Name="GeoData" Class="GeoDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=GeoData;User ID=root" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GeoDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Countries" Member="Countries">
    <Type Name="Country" Id="ID1">
      <Column Name="ISO" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="EquivalentFipsCode" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="ISO3" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="[ISO-Numeric]" Member="ISO_Numeric" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fips" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="Capital" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="[Area(in sq km)]" Member="Area" Storage="_Area_in_sq_km_" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Population" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Continent" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="tld" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="CurrencyCode" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="CurrencyName" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="[Postal Code Format]" Member="Postal_Code_Format" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="[Postal Code Regex]" Member="Postal_Code_Regex" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Languages" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="geonameid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="neighbours" Type="System.String" DbType="VarChar(41)" CanBeNull="true" />
      <Column Name="GeoData" Type="Microsoft.SqlServer.Types.SqlGeometry" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cities" Member="Cities">
    <Type Name="City" Id="ID2">
      <Column Name="geonameid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="asciiname" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="alternatenames" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="feature_class" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="feature_code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="country_code" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="cc2" Type="System.String" DbType="Char(60)" CanBeNull="true" />
      <Column Name="admin1_code" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="admin2_code" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="admin3_code" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="admin4_code" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="population" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="elevation" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gtopo30" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="timezone" Type="System.String" DbType="Char(31)" CanBeNull="true" />
      <Column Name="geog" Member="GeoData" Type="Microsoft.SqlServer.Types.SqlGeography" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.USA_States" Member="USA_States">
    <Type Name="USA_State" Id="ID3">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fips" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TwoDigitId" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="GeoData" Type="Microsoft.SqlServer.Types.SqlGeography" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.GetCountry" Method="GetCountry">
    <Parameter Name="lat" Type="System.Double" DbType="Float" />
    <Parameter Name="lng" Type="System.Double" DbType="Float" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.GetNearestCity" Method="GetNearestCity">
    <Parameter Name="lat" Type="System.Double" DbType="Float" />
    <Parameter Name="lng" Type="System.Double" DbType="Float" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.GetUSAState" Method="GetUSAState">
    <Parameter Name="lat" Type="System.Double" DbType="Float" />
    <Parameter Name="lng" Type="System.Double" DbType="Float" />
    <ElementType IdRef="ID3" />
  </Function>
</Database>