//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusIM.NexusCore {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLocationData", Namespace="http://schemas.datacontract.org/2004/07/NexusCore.DataContracts")]
    [System.SerializableAttribute()]
    public partial class UserLocationData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccuracyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReverseGeocodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NexusIM.NexusCore.LocationServiceType ServiceTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Accuracy {
            get {
                return this.AccuracyField;
            }
            set {
                if ((this.AccuracyField.Equals(value) != true)) {
                    this.AccuracyField = value;
                    this.RaisePropertyChanged("Accuracy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdated {
            get {
                return this.LastUpdatedField;
            }
            set {
                if ((this.LastUpdatedField.Equals(value) != true)) {
                    this.LastUpdatedField = value;
                    this.RaisePropertyChanged("LastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReverseGeocode {
            get {
                return this.ReverseGeocodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReverseGeocodeField, value) != true)) {
                    this.ReverseGeocodeField = value;
                    this.RaisePropertyChanged("ReverseGeocode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowId {
            get {
                return this.RowIdField;
            }
            set {
                if ((this.RowIdField.Equals(value) != true)) {
                    this.RowIdField = value;
                    this.RaisePropertyChanged("RowId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NexusIM.NexusCore.LocationServiceType ServiceType {
            get {
                return this.ServiceTypeField;
            }
            set {
                if ((this.ServiceTypeField.Equals(value) != true)) {
                    this.ServiceTypeField = value;
                    this.RaisePropertyChanged("ServiceType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationServiceType", Namespace="http://schemas.datacontract.org/2004/07/NexusCore.DataContracts")]
    public enum LocationServiceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GoogleLatitude = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FireEagle = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactLocationInfo", Namespace="http://schemas.datacontract.org/2004/07/NexusCore.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ContactLocationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NexusIM.NexusCore.AccountInfo AccountInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MessagableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NexusIM.NexusCore.LocationServiceType ServiceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NexusIM.NexusCore.AccountInfo AccountInfo {
            get {
                return this.AccountInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountInfoField, value) != true)) {
                    this.AccountInfoField = value;
                    this.RaisePropertyChanged("AccountInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Messagable {
            get {
                return this.MessagableField;
            }
            set {
                if ((this.MessagableField.Equals(value) != true)) {
                    this.MessagableField = value;
                    this.RaisePropertyChanged("Messagable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NexusIM.NexusCore.LocationServiceType ServiceType {
            get {
                return this.ServiceTypeField;
            }
            set {
                if ((this.ServiceTypeField.Equals(value) != true)) {
                    this.ServiceTypeField = value;
                    this.RaisePropertyChanged("ServiceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInfo", Namespace="com.nexus-im")]
    [System.SerializableAttribute()]
    public partial class AccountInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProtocolTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InstantMessage.IMProtocolStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((this.GuidField.Equals(value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProtocolType {
            get {
                return this.ProtocolTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProtocolTypeField, value) != true)) {
                    this.ProtocolTypeField = value;
                    this.RaisePropertyChanged("ProtocolType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Server {
            get {
                return this.ServerField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerField, value) != true)) {
                    this.ServerField = value;
                    this.RaisePropertyChanged("Server");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InstantMessage.IMProtocolStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyAccountInformation", Namespace="http://schemas.datacontract.org/2004/07/NexusCore.DataContracts")]
    [System.SerializableAttribute()]
    public partial class MyAccountInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mFirstName {
            get {
                return this.mFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.mFirstNameField, value) != true)) {
                    this.mFirstNameField = value;
                    this.RaisePropertyChanged("mFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mUsername {
            get {
                return this.mUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.mUsernameField, value) != true)) {
                    this.mUsernameField = value;
                    this.RaisePropertyChanged("mUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="com.nexusim.core", ConfigurationName="NexusCore.CoreService")]
    public interface CoreService {
        
        // CODEGEN: Generating message contract since the wrapper namespace () of message LogoutRequest does not match the default value (com.nexusim.core)
        [System.ServiceModel.OperationContractAttribute(Action="urn:JSCoreService/Logout", ReplyAction="urn:JSCoreService/LogoutResponse")]
        NexusIM.NexusCore.LogoutResponse Logout(NexusIM.NexusCore.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:JSCoreService/Logout", ReplyAction="urn:JSCoreService/LogoutResponse")]
        System.IAsyncResult BeginLogout(NexusIM.NexusCore.LogoutRequest request, System.AsyncCallback callback, object asyncState);
        
        NexusIM.NexusCore.LogoutResponse EndLogout(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since the wrapper namespace () of message GetLocationRequest does not match the default value (com.nexusim.core)
        [System.ServiceModel.OperationContractAttribute(Action="urn:JSCoreService/GetLocation", ReplyAction="urn:JSCoreService/GetLocationResponse")]
        NexusIM.NexusCore.GetLocationResponse GetLocation(NexusIM.NexusCore.GetLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:JSCoreService/GetLocation", ReplyAction="urn:JSCoreService/GetLocationResponse")]
        System.IAsyncResult BeginGetLocation(NexusIM.NexusCore.GetLocationRequest request, System.AsyncCallback callback, object asyncState);
        
        NexusIM.NexusCore.GetLocationResponse EndGetLocation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.nexusim.core/CoreService/Login", ReplyAction="com.nexusim.core/CoreService/LoginResponse")]
        void Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="com.nexusim.core/CoreService/Login", ReplyAction="com.nexusim.core/CoreService/LoginResponse")]
        System.IAsyncResult BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState);
        
        void EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.nexusim.core/CoreService/CookieLogin", ReplyAction="com.nexusim.core/CoreService/CookieLoginResponse")]
        string CookieLogin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="com.nexusim.core/CoreService/CookieLogin", ReplyAction="com.nexusim.core/CoreService/CookieLoginResponse")]
        System.IAsyncResult BeginCookieLogin(string username, string password, System.AsyncCallback callback, object asyncState);
        
        string EndCookieLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.nexusim.core/CoreService/LoginWithToken", ReplyAction="com.nexusim.core/CoreService/LoginWithTokenResponse")]
        void LoginWithToken(string token);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="com.nexusim.core/CoreService/LoginWithToken", ReplyAction="com.nexusim.core/CoreService/LoginWithTokenResponse")]
        System.IAsyncResult BeginLoginWithToken(string token, System.AsyncCallback callback, object asyncState);
        
        void EndLoginWithToken(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.nexusim.core/CoreService/GetLocationData", ReplyAction="com.nexusim.core/CoreService/GetLocationDataResponse")]
        System.Collections.Generic.List<NexusIM.NexusCore.ContactLocationInfo> GetLocationData();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="com.nexusim.core/CoreService/GetLocationData", ReplyAction="com.nexusim.core/CoreService/GetLocationDataResponse")]
        System.IAsyncResult BeginGetLocationData(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<NexusIM.NexusCore.ContactLocationInfo> EndGetLocationData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.nexusim.core/CoreService/GetMultipleLocations", ReplyAction="com.nexusim.core/CoreService/GetMultipleLocationsResponse")]
        System.Collections.Generic.List<NexusIM.NexusCore.UserLocationData> GetMultipleLocations(System.Collections.Generic.List<int> rowIds);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="com.nexusim.core/CoreService/GetMultipleLocations", ReplyAction="com.nexusim.core/CoreService/GetMultipleLocationsResponse")]
        System.IAsyncResult BeginGetMultipleLocations(System.Collections.Generic.List<int> rowIds, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<NexusIM.NexusCore.UserLocationData> EndGetMultipleLocations(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.nexusim.core/CoreService/GetAccounts", ReplyAction="com.nexusim.core/CoreService/GetAccountsResponse")]
        System.Collections.Generic.List<NexusIM.NexusCore.AccountInfo> GetAccounts();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="com.nexusim.core/CoreService/GetAccounts", ReplyAction="com.nexusim.core/CoreService/GetAccountsResponse")]
        System.IAsyncResult BeginGetAccounts(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<NexusIM.NexusCore.AccountInfo> EndGetAccounts(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.nexusim.core/CoreService/GetMyAccountInfo", ReplyAction="com.nexusim.core/CoreService/GetMyAccountInfoResponse")]
        NexusIM.NexusCore.MyAccountInformation GetMyAccountInfo();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="com.nexusim.core/CoreService/GetMyAccountInfo", ReplyAction="com.nexusim.core/CoreService/GetMyAccountInfoResponse")]
        System.IAsyncResult BeginGetMyAccountInfo(System.AsyncCallback callback, object asyncState);
        
        NexusIM.NexusCore.MyAccountInformation EndGetMyAccountInfo(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logout", WrapperNamespace="", IsWrapped=true)]
    public partial class LogoutRequest {
        
        public LogoutRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class LogoutResponse {
        
        public LogoutResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLocation", WrapperNamespace="", IsWrapped=true)]
    public partial class GetLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int rowId;
        
        public GetLocationRequest() {
        }
        
        public GetLocationRequest(int rowId) {
            this.rowId = rowId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLocationResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class GetLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public NexusIM.NexusCore.UserLocationData GetLocationResult;
        
        public GetLocationResponse() {
        }
        
        public GetLocationResponse(NexusIM.NexusCore.UserLocationData GetLocationResult) {
            this.GetLocationResult = GetLocationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CoreServiceChannel : NexusIM.NexusCore.CoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public NexusIM.NexusCore.UserLocationData Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((NexusIM.NexusCore.UserLocationData)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CookieLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CookieLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLocationDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLocationDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<NexusIM.NexusCore.ContactLocationInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<NexusIM.NexusCore.ContactLocationInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMultipleLocationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMultipleLocationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<NexusIM.NexusCore.UserLocationData> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<NexusIM.NexusCore.UserLocationData>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAccountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAccountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<NexusIM.NexusCore.AccountInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<NexusIM.NexusCore.AccountInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMyAccountInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMyAccountInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public NexusIM.NexusCore.MyAccountInformation Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((NexusIM.NexusCore.MyAccountInformation)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreServiceClient : System.ServiceModel.ClientBase<NexusIM.NexusCore.CoreService>, NexusIM.NexusCore.CoreService {
        
        private BeginOperationDelegate onBeginLogoutDelegate;
        
        private EndOperationDelegate onEndLogoutDelegate;
        
        private System.Threading.SendOrPostCallback onLogoutCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLocationDelegate;
        
        private EndOperationDelegate onEndGetLocationDelegate;
        
        private System.Threading.SendOrPostCallback onGetLocationCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginCookieLoginDelegate;
        
        private EndOperationDelegate onEndCookieLoginDelegate;
        
        private System.Threading.SendOrPostCallback onCookieLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoginWithTokenDelegate;
        
        private EndOperationDelegate onEndLoginWithTokenDelegate;
        
        private System.Threading.SendOrPostCallback onLoginWithTokenCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLocationDataDelegate;
        
        private EndOperationDelegate onEndGetLocationDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetLocationDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMultipleLocationsDelegate;
        
        private EndOperationDelegate onEndGetMultipleLocationsDelegate;
        
        private System.Threading.SendOrPostCallback onGetMultipleLocationsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAccountsDelegate;
        
        private EndOperationDelegate onEndGetAccountsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAccountsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMyAccountInfoDelegate;
        
        private EndOperationDelegate onEndGetMyAccountInfoDelegate;
        
        private System.Threading.SendOrPostCallback onGetMyAccountInfoCompletedDelegate;
        
        public CoreServiceClient() {
        }
        
        public CoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> LogoutCompleted;
        
        public event System.EventHandler<GetLocationCompletedEventArgs> GetLocationCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<CookieLoginCompletedEventArgs> CookieLoginCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> LoginWithTokenCompleted;
        
        public event System.EventHandler<GetLocationDataCompletedEventArgs> GetLocationDataCompleted;
        
        public event System.EventHandler<GetMultipleLocationsCompletedEventArgs> GetMultipleLocationsCompleted;
        
        public event System.EventHandler<GetAccountsCompletedEventArgs> GetAccountsCompleted;
        
        public event System.EventHandler<GetMyAccountInfoCompletedEventArgs> GetMyAccountInfoCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NexusIM.NexusCore.LogoutResponse NexusIM.NexusCore.CoreService.Logout(NexusIM.NexusCore.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public void Logout() {
            NexusIM.NexusCore.LogoutRequest inValue = new NexusIM.NexusCore.LogoutRequest();
            NexusIM.NexusCore.LogoutResponse retVal = ((NexusIM.NexusCore.CoreService)(this)).Logout(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NexusIM.NexusCore.CoreService.BeginLogout(NexusIM.NexusCore.LogoutRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogout(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLogout(System.AsyncCallback callback, object asyncState) {
            NexusIM.NexusCore.LogoutRequest inValue = new NexusIM.NexusCore.LogoutRequest();
            return ((NexusIM.NexusCore.CoreService)(this)).BeginLogout(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NexusIM.NexusCore.LogoutResponse NexusIM.NexusCore.CoreService.EndLogout(System.IAsyncResult result) {
            return base.Channel.EndLogout(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndLogout(System.IAsyncResult result) {
            NexusIM.NexusCore.LogoutResponse retVal = ((NexusIM.NexusCore.CoreService)(this)).EndLogout(result);
        }
        
        private System.IAsyncResult OnBeginLogout(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginLogout(callback, asyncState);
        }
        
        private object[] OnEndLogout(System.IAsyncResult result) {
            this.EndLogout(result);
            return null;
        }
        
        private void OnLogoutCompleted(object state) {
            if ((this.LogoutCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LogoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LogoutAsync() {
            this.LogoutAsync(null);
        }
        
        public void LogoutAsync(object userState) {
            if ((this.onBeginLogoutDelegate == null)) {
                this.onBeginLogoutDelegate = new BeginOperationDelegate(this.OnBeginLogout);
            }
            if ((this.onEndLogoutDelegate == null)) {
                this.onEndLogoutDelegate = new EndOperationDelegate(this.OnEndLogout);
            }
            if ((this.onLogoutCompletedDelegate == null)) {
                this.onLogoutCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogoutCompleted);
            }
            base.InvokeAsync(this.onBeginLogoutDelegate, null, this.onEndLogoutDelegate, this.onLogoutCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NexusIM.NexusCore.GetLocationResponse NexusIM.NexusCore.CoreService.GetLocation(NexusIM.NexusCore.GetLocationRequest request) {
            return base.Channel.GetLocation(request);
        }
        
        public NexusIM.NexusCore.UserLocationData GetLocation(int rowId) {
            NexusIM.NexusCore.GetLocationRequest inValue = new NexusIM.NexusCore.GetLocationRequest();
            inValue.rowId = rowId;
            NexusIM.NexusCore.GetLocationResponse retVal = ((NexusIM.NexusCore.CoreService)(this)).GetLocation(inValue);
            return retVal.GetLocationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NexusIM.NexusCore.CoreService.BeginGetLocation(NexusIM.NexusCore.GetLocationRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLocation(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetLocation(int rowId, System.AsyncCallback callback, object asyncState) {
            NexusIM.NexusCore.GetLocationRequest inValue = new NexusIM.NexusCore.GetLocationRequest();
            inValue.rowId = rowId;
            return ((NexusIM.NexusCore.CoreService)(this)).BeginGetLocation(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NexusIM.NexusCore.GetLocationResponse NexusIM.NexusCore.CoreService.EndGetLocation(System.IAsyncResult result) {
            return base.Channel.EndGetLocation(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public NexusIM.NexusCore.UserLocationData EndGetLocation(System.IAsyncResult result) {
            NexusIM.NexusCore.GetLocationResponse retVal = ((NexusIM.NexusCore.CoreService)(this)).EndGetLocation(result);
            return retVal.GetLocationResult;
        }
        
        private System.IAsyncResult OnBeginGetLocation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int rowId = ((int)(inValues[0]));
            return this.BeginGetLocation(rowId, callback, asyncState);
        }
        
        private object[] OnEndGetLocation(System.IAsyncResult result) {
            NexusIM.NexusCore.UserLocationData retVal = this.EndGetLocation(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLocationCompleted(object state) {
            if ((this.GetLocationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLocationCompleted(this, new GetLocationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLocationAsync(int rowId) {
            this.GetLocationAsync(rowId, null);
        }
        
        public void GetLocationAsync(int rowId, object userState) {
            if ((this.onBeginGetLocationDelegate == null)) {
                this.onBeginGetLocationDelegate = new BeginOperationDelegate(this.OnBeginGetLocation);
            }
            if ((this.onEndGetLocationDelegate == null)) {
                this.onEndGetLocationDelegate = new EndOperationDelegate(this.OnEndGetLocation);
            }
            if ((this.onGetLocationCompletedDelegate == null)) {
                this.onGetLocationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLocationCompleted);
            }
            base.InvokeAsync(this.onBeginGetLocationDelegate, new object[] {
                        rowId}, this.onEndGetLocationDelegate, this.onGetLocationCompletedDelegate, userState);
        }
        
        public void Login(string username, string password) {
            base.Channel.Login(username, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(username, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndLogin(System.IAsyncResult result) {
            base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginLogin(username, password, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            this.EndLogin(result);
            return null;
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string username, string password) {
            this.LoginAsync(username, password, null);
        }
        
        public void LoginAsync(string username, string password, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        username,
                        password}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        public string CookieLogin(string username, string password) {
            return base.Channel.CookieLogin(username, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCookieLogin(string username, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCookieLogin(username, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndCookieLogin(System.IAsyncResult result) {
            return base.Channel.EndCookieLogin(result);
        }
        
        private System.IAsyncResult OnBeginCookieLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginCookieLogin(username, password, callback, asyncState);
        }
        
        private object[] OnEndCookieLogin(System.IAsyncResult result) {
            string retVal = this.EndCookieLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCookieLoginCompleted(object state) {
            if ((this.CookieLoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CookieLoginCompleted(this, new CookieLoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CookieLoginAsync(string username, string password) {
            this.CookieLoginAsync(username, password, null);
        }
        
        public void CookieLoginAsync(string username, string password, object userState) {
            if ((this.onBeginCookieLoginDelegate == null)) {
                this.onBeginCookieLoginDelegate = new BeginOperationDelegate(this.OnBeginCookieLogin);
            }
            if ((this.onEndCookieLoginDelegate == null)) {
                this.onEndCookieLoginDelegate = new EndOperationDelegate(this.OnEndCookieLogin);
            }
            if ((this.onCookieLoginCompletedDelegate == null)) {
                this.onCookieLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCookieLoginCompleted);
            }
            base.InvokeAsync(this.onBeginCookieLoginDelegate, new object[] {
                        username,
                        password}, this.onEndCookieLoginDelegate, this.onCookieLoginCompletedDelegate, userState);
        }
        
        public void LoginWithToken(string token) {
            base.Channel.LoginWithToken(token);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLoginWithToken(string token, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoginWithToken(token, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndLoginWithToken(System.IAsyncResult result) {
            base.Channel.EndLoginWithToken(result);
        }
        
        private System.IAsyncResult OnBeginLoginWithToken(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string token = ((string)(inValues[0]));
            return this.BeginLoginWithToken(token, callback, asyncState);
        }
        
        private object[] OnEndLoginWithToken(System.IAsyncResult result) {
            this.EndLoginWithToken(result);
            return null;
        }
        
        private void OnLoginWithTokenCompleted(object state) {
            if ((this.LoginWithTokenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginWithTokenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginWithTokenAsync(string token) {
            this.LoginWithTokenAsync(token, null);
        }
        
        public void LoginWithTokenAsync(string token, object userState) {
            if ((this.onBeginLoginWithTokenDelegate == null)) {
                this.onBeginLoginWithTokenDelegate = new BeginOperationDelegate(this.OnBeginLoginWithToken);
            }
            if ((this.onEndLoginWithTokenDelegate == null)) {
                this.onEndLoginWithTokenDelegate = new EndOperationDelegate(this.OnEndLoginWithToken);
            }
            if ((this.onLoginWithTokenCompletedDelegate == null)) {
                this.onLoginWithTokenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginWithTokenCompleted);
            }
            base.InvokeAsync(this.onBeginLoginWithTokenDelegate, new object[] {
                        token}, this.onEndLoginWithTokenDelegate, this.onLoginWithTokenCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<NexusIM.NexusCore.ContactLocationInfo> GetLocationData() {
            return base.Channel.GetLocationData();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetLocationData(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLocationData(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<NexusIM.NexusCore.ContactLocationInfo> EndGetLocationData(System.IAsyncResult result) {
            return base.Channel.EndGetLocationData(result);
        }
        
        private System.IAsyncResult OnBeginGetLocationData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetLocationData(callback, asyncState);
        }
        
        private object[] OnEndGetLocationData(System.IAsyncResult result) {
            System.Collections.Generic.List<NexusIM.NexusCore.ContactLocationInfo> retVal = this.EndGetLocationData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLocationDataCompleted(object state) {
            if ((this.GetLocationDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLocationDataCompleted(this, new GetLocationDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLocationDataAsync() {
            this.GetLocationDataAsync(null);
        }
        
        public void GetLocationDataAsync(object userState) {
            if ((this.onBeginGetLocationDataDelegate == null)) {
                this.onBeginGetLocationDataDelegate = new BeginOperationDelegate(this.OnBeginGetLocationData);
            }
            if ((this.onEndGetLocationDataDelegate == null)) {
                this.onEndGetLocationDataDelegate = new EndOperationDelegate(this.OnEndGetLocationData);
            }
            if ((this.onGetLocationDataCompletedDelegate == null)) {
                this.onGetLocationDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLocationDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetLocationDataDelegate, null, this.onEndGetLocationDataDelegate, this.onGetLocationDataCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<NexusIM.NexusCore.UserLocationData> GetMultipleLocations(System.Collections.Generic.List<int> rowIds) {
            return base.Channel.GetMultipleLocations(rowIds);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetMultipleLocations(System.Collections.Generic.List<int> rowIds, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMultipleLocations(rowIds, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<NexusIM.NexusCore.UserLocationData> EndGetMultipleLocations(System.IAsyncResult result) {
            return base.Channel.EndGetMultipleLocations(result);
        }
        
        private System.IAsyncResult OnBeginGetMultipleLocations(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.Generic.List<int> rowIds = ((System.Collections.Generic.List<int>)(inValues[0]));
            return this.BeginGetMultipleLocations(rowIds, callback, asyncState);
        }
        
        private object[] OnEndGetMultipleLocations(System.IAsyncResult result) {
            System.Collections.Generic.List<NexusIM.NexusCore.UserLocationData> retVal = this.EndGetMultipleLocations(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMultipleLocationsCompleted(object state) {
            if ((this.GetMultipleLocationsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMultipleLocationsCompleted(this, new GetMultipleLocationsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMultipleLocationsAsync(System.Collections.Generic.List<int> rowIds) {
            this.GetMultipleLocationsAsync(rowIds, null);
        }
        
        public void GetMultipleLocationsAsync(System.Collections.Generic.List<int> rowIds, object userState) {
            if ((this.onBeginGetMultipleLocationsDelegate == null)) {
                this.onBeginGetMultipleLocationsDelegate = new BeginOperationDelegate(this.OnBeginGetMultipleLocations);
            }
            if ((this.onEndGetMultipleLocationsDelegate == null)) {
                this.onEndGetMultipleLocationsDelegate = new EndOperationDelegate(this.OnEndGetMultipleLocations);
            }
            if ((this.onGetMultipleLocationsCompletedDelegate == null)) {
                this.onGetMultipleLocationsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMultipleLocationsCompleted);
            }
            base.InvokeAsync(this.onBeginGetMultipleLocationsDelegate, new object[] {
                        rowIds}, this.onEndGetMultipleLocationsDelegate, this.onGetMultipleLocationsCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<NexusIM.NexusCore.AccountInfo> GetAccounts() {
            return base.Channel.GetAccounts();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAccounts(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAccounts(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<NexusIM.NexusCore.AccountInfo> EndGetAccounts(System.IAsyncResult result) {
            return base.Channel.EndGetAccounts(result);
        }
        
        private System.IAsyncResult OnBeginGetAccounts(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAccounts(callback, asyncState);
        }
        
        private object[] OnEndGetAccounts(System.IAsyncResult result) {
            System.Collections.Generic.List<NexusIM.NexusCore.AccountInfo> retVal = this.EndGetAccounts(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAccountsCompleted(object state) {
            if ((this.GetAccountsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAccountsCompleted(this, new GetAccountsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAccountsAsync() {
            this.GetAccountsAsync(null);
        }
        
        public void GetAccountsAsync(object userState) {
            if ((this.onBeginGetAccountsDelegate == null)) {
                this.onBeginGetAccountsDelegate = new BeginOperationDelegate(this.OnBeginGetAccounts);
            }
            if ((this.onEndGetAccountsDelegate == null)) {
                this.onEndGetAccountsDelegate = new EndOperationDelegate(this.OnEndGetAccounts);
            }
            if ((this.onGetAccountsCompletedDelegate == null)) {
                this.onGetAccountsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAccountsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAccountsDelegate, null, this.onEndGetAccountsDelegate, this.onGetAccountsCompletedDelegate, userState);
        }
        
        public NexusIM.NexusCore.MyAccountInformation GetMyAccountInfo() {
            return base.Channel.GetMyAccountInfo();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetMyAccountInfo(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMyAccountInfo(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public NexusIM.NexusCore.MyAccountInformation EndGetMyAccountInfo(System.IAsyncResult result) {
            return base.Channel.EndGetMyAccountInfo(result);
        }
        
        private System.IAsyncResult OnBeginGetMyAccountInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetMyAccountInfo(callback, asyncState);
        }
        
        private object[] OnEndGetMyAccountInfo(System.IAsyncResult result) {
            NexusIM.NexusCore.MyAccountInformation retVal = this.EndGetMyAccountInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMyAccountInfoCompleted(object state) {
            if ((this.GetMyAccountInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMyAccountInfoCompleted(this, new GetMyAccountInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMyAccountInfoAsync() {
            this.GetMyAccountInfoAsync(null);
        }
        
        public void GetMyAccountInfoAsync(object userState) {
            if ((this.onBeginGetMyAccountInfoDelegate == null)) {
                this.onBeginGetMyAccountInfoDelegate = new BeginOperationDelegate(this.OnBeginGetMyAccountInfo);
            }
            if ((this.onEndGetMyAccountInfoDelegate == null)) {
                this.onEndGetMyAccountInfoDelegate = new EndOperationDelegate(this.OnEndGetMyAccountInfo);
            }
            if ((this.onGetMyAccountInfoCompletedDelegate == null)) {
                this.onGetMyAccountInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMyAccountInfoCompleted);
            }
            base.InvokeAsync(this.onBeginGetMyAccountInfoDelegate, null, this.onEndGetMyAccountInfoDelegate, this.onGetMyAccountInfoCompletedDelegate, userState);
        }
    }
}
