<?xml version="1.0" encoding="utf-8"?><Database Name="NexusCore" Class="userdbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=NexusCore;Integrated Security=True;Application Name=NexusWeb" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NexusCoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AuthTokens" Member="AuthTokens">
    <Type Name="AuthToken">
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="token" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="expires" Storage="_lastuse" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Association Name="User_AuthToken" Member="User" ThisKey="userid" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Devices" Member="Devices">
    <Type Name="Device">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="devicetype" Storage="_type" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="lastseen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lastsignin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="logintoken" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Friends" Member="Friends">
    <Type Name="Friend">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="friendid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="displayname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_Friend" Member="User" ThisKey="userid" OtherKey="id" Type="User" IsForeignKey="true" />
      <Association Name="User_Friend1" Member="User1" ThisKey="friendid" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LocationPrivacy" Member="LocationPrivacies">
    <Type Name="LocationPrivacy">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="locationid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="accountid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_LocationPrivacy" Member="User" ThisKey="userid" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Requests" Member="Requests">
    <Type Name="Request">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="recipient" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="requesttype" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserLocation" Member="UserLocations">
    <Type Name="UserLocation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="service" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="identifier" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_UserLocation" Member="User" ThisKey="userid" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeviceTypes" Member="DeviceTypes">
    <Type Name="DeviceType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="LongName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DownloadUrl" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PlatformMinVersion" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ProductMaker" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ProductUrl" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="RequiresCustomPush" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StatusUpdates" Member="StatusUpdates">
    <Type Name="StatusUpdate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MessageBody" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="GeoTag" Type="Microsoft.SqlServer.Types.SqlGeography" CanBeNull="true" />
      <Column Name="GeoTagAccuracy" Type="System.Single" DbType="float" CanBeNull="true" />
      <Association Name="StatusUpdate_ArticleComment" Member="ArticleComments" Storage="_StatusUpdateComments" ThisKey="Id" OtherKey="ArticleId" Type="ArticleComment" />
      <Association Name="User_StatusUpdate" Member="User" ThisKey="Userid" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserAccessControl" Member="UserAccessControls">
    <Type Name="UserAccessControl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ControlId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccessPermitted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AccessControl" Member="AccessControls">
    <Type Name="AccessControl">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IsBlacklist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PermitEveryone" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PermitFriends" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PermitFriendsOfFriends" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Albums" Member="Albums">
    <Type Name="Album">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AclIsBlacklist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AclControlId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Album_Photo" Member="Photos" ThisKey="Id" OtherKey="AlbumId" Type="Photo" />
      <Association Name="User_Album" Member="User" ThisKey="OwnerUserID" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Accounts" Member="Accounts">
    <Type Name="Account">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="guid" Type="System.String" DbType="Char(36) NOT NULL" CanBeNull="false" />
      <Column Name="acctype" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="server" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LoginState" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HostComputer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_Account" Member="User" ThisKey="userid" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Photos" Member="Photos">
    <Type Name="Photo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AlbumId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhotoData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Album_Photo" Member="Album" ThisKey="AlbumId" OtherKey="Id" Type="Album" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="Char(64) NOT NULL" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="locationsharestate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="canlogin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="emailauthtoken" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="dateregistered" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="lastseen" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="friendlistversion" Member="FriendListVersion" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DisplayImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DefaultPhotoAcl" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountListVersion" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="IsIMSignedIn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_AuthToken" Member="AuthTokens" ThisKey="id" OtherKey="userid" Type="AuthToken" />
      <Association Name="User_Friend" Member="Friends" ThisKey="id" OtherKey="userid" Type="Friend" />
      <Association Name="User_Friend1" Member="Friends1" ThisKey="id" OtherKey="friendid" Type="Friend" />
      <Association Name="User_LocationPrivacy" Member="LocationPrivacies" ThisKey="id" OtherKey="userid" Type="LocationPrivacy" />
      <Association Name="User_UserLocation" Member="UserLocations" ThisKey="id" OtherKey="userid" Type="UserLocation" />
      <Association Name="User_StatusUpdate" Member="StatusUpdates" ThisKey="id" OtherKey="Userid" Type="StatusUpdate" />
      <Association Name="User_Account" Member="Accounts" ThisKey="id" OtherKey="userid" Type="Account" />
      <Association Name="User_ArticleComment" Member="ArticleComments" ThisKey="id" OtherKey="UserId" Type="ArticleComment" />
      <Association Name="User_Album" Member="Albums" ThisKey="id" OtherKey="OwnerUserID" Type="Album" />
    </Type>
  </Table>
  <Table Name="dbo.ArticleComments" Member="ArticleComments">
    <Type Name="ArticleComment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ArticleType" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ArticleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MessageBody" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_ArticleComment" Member="User" ThisKey="UserId" OtherKey="id" Type="User" IsForeignKey="true" />
      <Association Name="StatusUpdate_ArticleComment" Member="StatusUpdate" ThisKey="ArticleId" OtherKey="Id" Type="StatusUpdate" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GeoTagStatusMessage" Method="GeoTagStatusMessage">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="lat" Type="System.Double" DbType="Float" />
    <Parameter Name="lng" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GeoTagAltStatusMessage" Method="GeoTagAltStatusMessage">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="lat" Type="System.Double" DbType="Float" />
    <Parameter Name="lng" Type="System.Double" DbType="Float" />
    <Parameter Name="alt" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
</Database>