//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusWeb.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Used in fireeagle_auth.aspx to request the first token as per OAuth documentation
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Used in fireeagle_auth.aspx to request the first token as per OAuth documentation" +
            "")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://fireeagle.yahooapis.com/oauth/request_token")]
        public global::System.Uri FireEagle_UnauthorizedRequestToken {
            get {
                return ((global::System.Uri)(this["FireEagle_UnauthorizedRequestToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SmkThhsxhnJK")]
        public string FireEagle_ConsumerKey {
            get {
                return ((string)(this["FireEagle_ConsumerKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zMsAXNg8lUyT0gXaWooJXgUMGgH5ZEB7")]
        public string FireEagle_ConsumerSecret {
            get {
                return ((string)(this["FireEagle_ConsumerSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A0iiaSMKqMvT")]
        public string FireEagle_GeneralPurposeToken {
            get {
                return ((string)(this["FireEagle_GeneralPurposeToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sGo8oITfBJsdC0WI3IIEKrzZZUBhPuD3")]
        public string FireEagle_GeneralPurposeSecret {
            get {
                return ((string)(this["FireEagle_GeneralPurposeSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1970-12-01")]
        public global::System.DateTime UnixEpoch {
            get {
                return ((global::System.DateTime)(this["UnixEpoch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6LdgTAwAAAAAACmYjmTcFFohp3HaMKGEvfJkF_xZ")]
        public string RecaptchaPublicKey {
            get {
                return ((string)(this["RecaptchaPublicKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6LdgTAwAAAAAANoXiFB7nbPttaOmalDuumyyNoX0")]
        public string RecaptchaPrivateKey {
            get {
                return ((string)(this["RecaptchaPrivateKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30d96384051f05491f8aa8f0d22f6361")]
        public string FacebookAPIKey {
            get {
                return ((string)(this["FacebookAPIKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("503ad85c38a4c767765ac3cdb4247e51")]
        public string FacebookSecret {
            get {
                return ((string)(this["FacebookSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int LongPollTimeout {
            get {
                return ((int)(this["LongPollTimeout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AsS2Xi9W1iyJWYJv67X3CnPtgqpQrITIGqlBqKBuSkRh0benHS3vkAaC2V-s_2nP")]
        public string BingMapsApiKey {
            get {
                return ((string)(this["BingMapsApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nexus-im.com")]
        public string GoogleOAuthConsumerKey {
            get {
                return ((string)(this["GoogleOAuthConsumerKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KQ9Wv2oRutAWOQ64uPGPsob7")]
        public string GoogleOAuthConsumerSecret {
            get {
                return ((string)(this["GoogleOAuthConsumerSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAppFabricCache {
            get {
                return ((bool)(this["EnableAppFabricCache"]));
            }
        }
        
        /// <summary>
        /// Regex match string to verify secure requests come from an authorized domain. Counter-CSRF This is designed for WCF method calls, not every web page.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Regex match string to verify secure requests come from an authorized domain. Coun" +
            "ter-CSRF This is designed for WCF method calls, not every web page.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(localhost|im.adrensoftware.com|5.64.115.83|dev.nexus-im.com|pub.nexus-im.com)")]
        public string SecureReferrerAcceptRegex {
            get {
                return ((string)(this["SecureReferrerAcceptRegex"]));
            }
        }
    }
}
