<?xml version="1.0" encoding="utf-8"?><Database Name="UserData" Class="UserProfile" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Accounts">
    <Type Name="Account">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountType" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
    </Type>
  </Table>
</Database>