<?xml version="1.0" encoding="utf-8"?><Database Name="UserProfile" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Accounts">
    <Type Name="Account">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountType" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AutoConnect" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Server" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="true" UpdateCheck="Never" />
      <Column Member="Port" Type="System.Int32" DbType="smallint" CanBeNull="true" UpdateCheck="WhenChanged" />
      <Association Name="Account_AccountSetting" Member="AccountSettings" ThisKey="Id" OtherKey="AccountId" Type="AccountSetting" />
      <Association Name="ChatWindowPool_Account" Member="ChatWindowPool" ThisKey="Id" OtherKey="AccountId" Type="ChatWindowPool" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="AccountSettings">
    <Type Name="AccountSetting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Key" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Account_AccountSetting" Member="Account" ThisKey="AccountId" OtherKey="Id" Type="Account" IsForeignKey="true" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="ChatWindowPools">
    <Type Name="ChatWindowPool">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PoolId" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="ChatWindowPool_Account" Member="Account" Storage="_Accounts" ThisKey="AccountId" OtherKey="Id" Type="Account" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="Settings">
    <Type Name="Setting">
      <Column Name="Key" Type="System.String" DbType="NVarChar(12) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>